name: OutlookAssignment
options:
  bundleIdPrefix: com.rmalhotra
targets:
  OutlookAssignment:
    type: application
    platform: [iOS]
    sources: OutlookAssignment
    scheme:
      gatherCoverageData: true
      testTargets:
        - OutlookAssignmentTests_$platform
  OutlookAssignmentTests:
    type: bundle.unit-test
    platform: [iOS]
    sources: OutlookAssignmentTests
    dependencies:
      - target: OutlookAssignmentTests_$platform