name: OutlookAssignment
options:
  bundleIdPrefix: com.rmalhotra
targets:
  OutlookAssignment:
    type: application
    platform: [iOS]
    sources: OutlookAssignment
    prebuildScripts:
      - path: ./env-script.sh
        name: environment initializer(make sure you set $API_KEY to your Forecast API Key
    scheme:
      gatherCoverageData: true
      testTargets:
        - OutlookAssignmentTests_$platform
  OutlookAssignmentTests:
    type: bundle.unit-test
    platform: [iOS]
    sources: OutlookAssignmentTests
    dependencies:
      - target: OutlookAssignmentTests_$platform